name: TFLint
on:
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

        with:
          tflint_version_file: .tool-versions

      - name: Run TFLint
        run: tflint --version
